# Generated by Django 3.1.1 on 2020-09-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=8),
        ),
    ]
