# Generated by Django 3.1.1 on 2020-10-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0004_mymodelwithfigure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shares',
            new_name='quantity',
        ),
    ]
