# Generated by Django 3.1.1 on 2020-10-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0009_stockorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cash_balance',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockorder',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
