# Generated by Django 3.1.1 on 2020-10-05 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_app', '0011_auto_20201004_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('order_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModelWithFigure',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stockorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='stockorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='stockorder',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='stockorder',
            name='user',
        ),
        migrations.AddField(
            model_name='stockorder',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trade_app.stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockorder',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trade_app.cart'),
            preserve_default=False,
        ),
    ]
