# Generated by Django 3.1.1 on 2020-10-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0012_auto_20201004_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockorder',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='stockorder',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockOrder',
        ),
    ]
