# Generated by Django 3.1.1 on 2020-10-08 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_app', '0014_cart_stock_stockorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockorder',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='stockorder',
            name='stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='action',
            field=models.CharField(default='buy', max_length=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='order_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='StockOrder',
        ),
    ]
