# Generated by Django 3.1.1 on 2020-10-13 20:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_app', '0015_auto_20201008_1047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='StockOrder',
        ),
    ]
